//
//  FeaturedWireframe.swift
//  MovieLib
//
//  Created by Roman Subrichak on 10/1/17.
//  Copyright (c) 2017 Roman Subrychak. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeaturedWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: FeaturedViewController) {
        let interactor = FeaturedInteractor()
        let presenter = FeaturedPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "FeaturedViewController") as! FeaturedViewController
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }
}

// MARK: - Extensions -

extension FeaturedWireframe: FeaturedWireframeInterface {

    func navigate(to option: FeaturedNavigationOption) {
    }
}
