//
//  FeaturedPresenter.swift
//  MovieLib
//
//  Created by Roman Subrichak on 10/1/17.
//  Copyright (c) 2017 Roman Subrychak. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeaturedPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: FeaturedViewInterface?
    fileprivate var _interactor: FeaturedInteractorInterface
    fileprivate var _wireframe: FeaturedWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: FeaturedWireframeInterface, view: FeaturedViewInterface, interactor: FeaturedInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension FeaturedPresenter: FeaturedPresenterInterface {
}
