//
//  FeaturedInteractor.swift
//  MovieLib
//
//  Created by Roman Subrichak on 10/1/17.
//  Copyright (c) 2017 Roman Subrychak. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FeaturedInteractor {
}

// MARK: - Extensions -

extension FeaturedInteractor: FeaturedInteractorInterface {
}
