//
//  FeaturedInterfaces.swift
//  MovieLib
//
//  Created by Roman Subrichak on 10/1/17.
//  Copyright (c) 2017 Roman Subrychak. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeaturedNavigationOption {
}

protocol FeaturedWireframeInterface: WireframeInterface {
    func navigate(to option: FeaturedNavigationOption)
}

protocol FeaturedViewInterface: ViewInterface {
}

protocol FeaturedPresenterInterface: PresenterInterface {
}

protocol FeaturedInteractorInterface: InteractorInterface {
}
