//
//  FeaturedViewController.swift
//  MovieLib
//
//  Created by Roman Subrichak on 10/1/17.
//  Copyright (c) 2017 Roman Subrychak. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeaturedViewController: UIViewController {

    // MARK: - Public properties -
	@IBOutlet var segmentedControl: UISegmentedControl!
	@IBOutlet var tableView: UITableView!

    var presenter: FeaturedPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
		title = "Featured"
		navigationController?.navigationBar.prefersLargeTitles = true
		
		let tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: 200))
		tableView.tableHeaderView = tableHeaderView
    }
	
}

// MARK: - Extensions -

extension FeaturedViewController: FeaturedViewInterface {
}
